# numpy practice session

In [1]:
# pip install numpy

In [2]:
# import this library in j.notebook
import numpy as np

# Creating an array using numpy

In [3]:
# 1-D array
food = np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [15]:
price = np.array ([3, 4, 5])
price

array([3, 4, 5])

In [11]:
# n diminsional array
type(price)

numpy.ndarray

In [12]:
type(food)

numpy.ndarray

In [13]:
len(price)

3

In [14]:
len(food)

3

In [20]:
# indexing starts from 0

price[0]

3

In [21]:
price[1]

4

In [19]:
price[2]

5

In [22]:
price[0:]

array([3, 4, 5])

In [24]:
food[1]

'Samosa'

In [25]:
price.mean()

4.0

## array methods

In [26]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [28]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [32]:
np.arange(0, 20, 2) #step size 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
np.linspace(0, 10, 5) # 5 numbers in total

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [35]:
np.linspace(0, 10, num=5) # 5 numbers in total

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
# specify data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [38]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array functions

In [40]:
a = np.array([10, 12, 15, 2, 4, 6, 100, 320, 0.5, 10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [42]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [44]:
b= np.array([10.2, 11.6, 1.2, 2.9, 56.6, 34.3, 91.2])
b

array([10.2, 11.6,  1.2,  2.9, 56.6, 34.3, 91.2])

In [47]:
# concatenate 2 arrays

c= np.concatenate((a, b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,  11.6,   1.2,   2.9,  56.6,  34.3,  91.2])

# 2-D arrays

In [48]:
a = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [55]:
b = np.array([[6, 7, 8, 9, 10], [10, 9, 8, 7, 6]])
b

array([[ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [60]:
# concatenate 

# axis = 0 implies that it is being done row-wise
# axis = 1 implies that it is being done column-wise


c= np.concatenate((a, b), axis=0)
c


array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [65]:
a = np.array([[[0, 1, 2, 3], # 2 diminsional
                [4, 5, 6, 7]],

                [[0, 1, 2, 3], # 2 diminsional
                [4, 5, 6, 7]],

                [[0 ,1 ,2, 3], # 2 dim
                [4, 5, 6, 7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [66]:
# to find the dimension
a.ndim # 3 dimenasional array of 2x4

3

In [73]:
type(a)

numpy.ndarray

In [72]:
b = np.array([[0, 1, 2], # 2 dimensional array of 3x3
                [4, 5, 6],
                 [8, 9, 10]])
b

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [71]:
# to find the dimension
b.ndim # 2 dimensional array of 3x3

2

In [74]:
type(b)

numpy.ndarray

In [76]:
# size (no of elements)

a = np.array([[[0, 1, 2, 3], # 3 diminsional array of 2x4
                [4, 5, 6, 7]],

                [[0, 1, 2, 3], 
                [4, 5, 6, 7]],

                [[0 ,1 ,2, 3], 
                [4, 5, 6, 7]]])

a.size

24

In [77]:
a.shape # 3 diminsional array of 2x4

(3, 2, 4)

In [80]:
a= np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [81]:
# reshape 3x2

b= a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [85]:
# reshape

np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [90]:
# convert 1D into 2D

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a.shape

(9,)

In [100]:
# row wise 2D conversion

a2 = a[np.newaxis, :]
a2

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [101]:
a2.shape

(1, 9)

In [97]:
a3 = a[:, np.newaxis]
a3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [98]:
a3.shape

(9, 1)

In [105]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
## array slicing

a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [108]:
a*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [109]:
a+3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [110]:
a.sum()

45

In [111]:
a.mean()

5.0